let game = new Game()
game.initialize('ARAGORN')

$(document).ready(function () {
  $('#playerName').text(game.player.returnAttribute('name'))
  $('#playerHealth').text(game.player.returnAttribute('health'))
  $('#playerArmour').text(game.player.returnAttribute('armor'))
  $('#playerStrength').text(game.player.returnAttribute('strength'))
  $('#playerDexterity').text(game.player.returnAttribute('dexterity'))
  $('#playerWeapon').text(game.player.returnAttribute('weaponName'))
  $('#armourType').text(game.player.returnAttribute('armorName'))
  $('#monsterHealth').text(game.monster.returnMonster('zombie').health)
  $('#monsterArmor').text(game.monster.returnMonster('zombie').armor)
  $('#output').html(game.readout.printReadout())

  $('#playerAttack').click(function () {
    game.combat.attackSequence()
    $('#playerName').text(game.player.returnAttribute('name'))
    $('#playerHealth').text(game.player.returnAttribute('health'))
    $('#playerArmour').text(game.player.returnAttribute('armor'))
    $('#playerStrength').text(game.player.returnAttribute('strength'))
    $('#playerDexterity').text(game.player.returnAttribute('dexterity'))
    $('#playerWeapon').text(game.player.returnAttribute('weaponName'))
    $('#armourType').text(game.player.returnAttribute('armorName'))
    $('#monsterHealth').text(game.monster.returnMonster('zombie').health)
    $('#monsterArmor').text(game.monster.returnMonster('zombie').armor)
    $('#output').html(game.readout.printReadout())
  })
})
